Added the test suite
cristian-vijelie/lib-nettle pull request #2
Opened 2020-12-04 13:50 UTC by cristian-vijelie

2020-12-05 11:26 UTC, craciunoiuc approved these changes
Hey Cristi,

The commits that add the test suite look pretty good. I did not see anything bad at first glance.

When you send them on the mailing list I will do another pass over everything and I will check if I missed anything. Maybe you can do the same before sending them, so we can avoid the need for a resubmision ;).

Cezar

2020-12-05 11:26 UTC, craciunoiuc commented on Makefile.uk
> +	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR)/testsuite && cp $^ $(LIBNETTLE_DIR) && touch $@)
I don't really see a reason to move al sources from the `testsuite` folder to the one above, but, if it works it works.

2020-12-05 12:01 UTC, cristian-vijelie commented on Makefile.uk
> +	$(call verbose_cmd,GEN,libnettle: $(notdir $@), cd $(LIBNETTLE_DIR)/testsuite && cp $^ $(LIBNETTLE_DIR) && touch $@)
Yes, that's the hack I was telling you about. If you look in the sources, they use some headers that are present in the folder above, but are used as being in the current folder. When libnettle builds, it changes the environment. So, to make unikraft build it, I had 3 options: modify every include to be #include "../something.h" via a patch, move the sources where the headers are, or copy the headers where the test sources are. I chose the 2nd option.

2020-12-05 12:10 UTC, craciunoiuc commented on Config.uk
> +if LIBNETTLE
Add something like this to mount a filesystem:
```
if PLAT_KVM
	select LIBUK9P
	select LIB9PFS
	select LIBVFSCORE_AUTOMOUNT_ROOTFS
	choice LIBVFSCORE_ROOTFS
		default LIBVFSCORE_ROOTFS_9PFS
	endchoice
```

2020-12-05 12:12 UTC, craciunoiuc requested changes
Hey again,

I just realized that a filesystem is needed to ensure 100% functionality on KVM. Please add something like what I suggested in the `Config.uk` file. Also, specify this in the readme.

Cezar

2020-12-05 14:52 UTC, craciunoiuc commented on Makefile.uk
> +-Wnomissing-prototypes -Wmissing-declarations -Wstrict-prototypes   \
```
gcc: error: unrecognized command line option ‘-Wnomissing-prototypes’; did you mean ‘-Wno-missing-prototypes’?
```

2021-01-28 16:32 UTC, craciunoiuc commented
Looks Good!

2021-01-28 16:34 UTC, craciunoiuc approved these changes
Looks good.

2021-01-28 16:47 UTC, merged